import { cobolParser } from "../parser/cobolParser";

export interface IRuleTokens {
    ruleId: number;
    values?: (number | string) [];
};

export const _RuleTokens: IRuleTokens[] = [
    // {   ruleId: cobolParser.RULE_cobol_source,
    //     values: [
    //         cobolParser.IDENTIFICATION,
    //     ]
    // },
    // {   ruleId: cobolParser.RULE_program,
    //     values: [
    //         cobolParser.IDENTIFICATION,
    //     ]
    // },
    {   ruleId: cobolParser.RULE_identification_division, 
        values: [
            cobolParser.IDENTIFICATION,
            cobolParser.DIVISION,
            cobolParser.PROGRAM_ID,
            cobolParser.AUTHOR,
            cobolParser.INSTALLATION,
            cobolParser.DATE_WRITTEN,
            cobolParser.DATE_COMPILED,
            cobolParser.SECURITY,
            cobolParser.OPTIONS,
            
            cobolParser.ENVIRONMENT,
            cobolParser.DATA,
            cobolParser.PROCEDURE,
            cobolParser.END,
        ]
    },
    {   ruleId: cobolParser.RULE_environment_division, 
        values: [
            cobolParser.ENVIRONMENT,
            cobolParser.DIVISION,
            cobolParser.CONFIGURATION,
            cobolParser.INPUT_OUTPUT,

            cobolParser.IDENTIFICATION,
            cobolParser.DATA,
            cobolParser.PROCEDURE,
            cobolParser.END,
        ]
    },
    {   ruleId: cobolParser.RULE_data_division, 
        values: [
            cobolParser.DATA,
            cobolParser.DIVISION,
        ]
    },
    {   ruleId: cobolParser.RULE_procedure_division, 
        values: [
            cobolParser.PROCEDURE,
            cobolParser.DIVISION,
        ]
    },
    {   ruleId: cobolParser.RULE_author, 
        values: [
            cobolParser.IDENTIFICATION,
            cobolParser.DIVISION,
            cobolParser.AUTHOR,
            cobolParser.INSTALLATION,
            cobolParser.DATE_WRITTEN,
            cobolParser.DATE_COMPILED,
            cobolParser.SECURITY,
            cobolParser.OPTIONS,
            
            cobolParser.ENVIRONMENT,
            cobolParser.DATA,
            cobolParser.PROCEDURE,
            cobolParser.END,
        ]
    },
    // {   ruleId: cobolParser.RULE_figurative_constant_witout_all_zero, },
    // {   ruleId: cobolParser.RULE_figurative_constant_zero, },
    // {   ruleId: cobolParser.RULE_figurative_constant_witout_all, },
    // {   ruleId: cobolParser.RULE_figurative_constant_witout_zero, },
    // {   ruleId: cobolParser.RULE_figurative_constant, },
    {   ruleId: cobolParser.RULE_end_program, 
        values: [
            cobolParser.IDENTIFICATION,
            cobolParser.END,
            cobolParser.PROGRAM,
        ]
    },
    {   ruleId: cobolParser.RULE_procedure_division_header, 
        values: [
            cobolParser.PROCEDURE,
            cobolParser.DIVISION,
            cobolParser.END,
            cobolParser.PROGRAM,
        ]
    },
// cobolParser.RULE_word_in_area_A,
// cobolParser.RULE_word_in_area_B,
// cobolParser.RULE_section,
// cobolParser.RULE_declaratives,
// cobolParser.RULE_end_declaratives,
// cobolParser.RULE_declaratives_section,
// cobolParser.RULE_paragraph,
// cobolParser.RULE_paragraph_name,
// cobolParser.RULE_use_statement,
// cobolParser.RULE_group_data_name,
// cobolParser.RULE_use_on,
// cobolParser.RULE_section_header,
// cobolParser.RULE_section_name,
// cobolParser.RULE_using,
// cobolParser.RULE_giving,
// cobolParser.RULE_statement,
// cobolParser.RULE_copy_statement,
// cobolParser.RULE_copy_replacing,
// cobolParser.RULE_record_name,
// cobolParser.RULE_library_name,
// cobolParser.RULE_text_name,
// cobolParser.RULE_replace_statement,
// cobolParser.RULE_write_statement,
// cobolParser.RULE_advance_value,
// cobolParser.RULE_advance_num,
// cobolParser.RULE_unstring_statement,
// cobolParser.RULE_unstring_tally_ctr,
// cobolParser.RULE_unstring_dest_clause,
// cobolParser.RULE_countr,
// cobolParser.RULE_dest_string,
// cobolParser.RULE_delim_dest,
// cobolParser.RULE_unstring_delim_clause,
// cobolParser.RULE_unstring_delim,
// cobolParser.RULE_unstring_src,
// cobolParser.RULE_unlock_statement,
// cobolParser.RULE_terminate_statement,
// cobolParser.RULE_suppress_statement,
// cobolParser.RULE_subtract_statement,
// cobolParser.RULE_sub_grp,
// cobolParser.RULE_sub_num,
// cobolParser.RULE_string_statement,
// cobolParser.RULE_string_pointer,
// cobolParser.RULE_string_dest,
// cobolParser.RULE_string_delim,
// cobolParser.RULE_string_src,
// cobolParser.RULE_stop_statement,
// cobolParser.RULE_stop_disp,
// cobolParser.RULE_start_statement,
// cobolParser.RULE_sort_key_data,
// cobolParser.RULE_sort_statement,
// cobolParser.RULE_sort_name,
// cobolParser.RULE_procedure_is,
// cobolParser.RULE_on_sort_key,
// cobolParser.RULE_sort_key,
// cobolParser.RULE_set_statement,
// cobolParser.RULE_set_statement_form1,
// cobolParser.RULE_set_statement_form2,
// cobolParser.RULE_set_statement_form3,
// cobolParser.RULE_set_statement_form4,
// cobolParser.RULE_set_statement_form5,
// cobolParser.RULE_set_statement_form6,
// cobolParser.RULE_set_increm,
// cobolParser.RULE_set_val,
// cobolParser.RULE_search_statement,
// cobolParser.RULE_search_condition,
// cobolParser.RULE_search_arg,
// cobolParser.RULE_search_elemnt,
// cobolParser.RULE_search_pointer,
// cobolParser.RULE_src_table,
// cobolParser.RULE_rewrite_statement,
// cobolParser.RULE_rewrite_rec_name,
// cobolParser.RULE_return_statement,
// cobolParser.RULE_smrg_file,
// cobolParser.RULE_release_statement,
// cobolParser.RULE_release_src_area,
// cobolParser.RULE_release_rec,
// cobolParser.RULE_record_statement,
// cobolParser.RULE_relation_type,
// cobolParser.RULE_path_name,
// cobolParser.RULE_read_statement,
// cobolParser.RULE_regard_allow,
// cobolParser.RULE_read_options,
// cobolParser.RULE_perform_statement,
// cobolParser.RULE_proc_thru_proc,
// cobolParser.RULE_perform_times,
// cobolParser.RULE_with_test,
// cobolParser.RULE_perform_until,
// cobolParser.RULE_perform_varying,
// cobolParser.RULE_perform_range,
// cobolParser.RULE_perform_increm,
// cobolParser.RULE_perform_init,
// cobolParser.RULE_perform_var,
// cobolParser.RULE_open_statement,
// cobolParser.RULE_open_definition,
// cobolParser.RULE_open_file_attributes,
// cobolParser.RULE_multiply_statement,
// cobolParser.RULE_mult_num,
// cobolParser.RULE_merge_statement,
// cobolParser.RULE_output_proc,
// cobolParser.RULE_first_proc,
// cobolParser.RULE_end_proc,
// cobolParser.RULE_giving_file,
// cobolParser.RULE_infile,
// cobolParser.RULE_merge_on,
// cobolParser.RULE_mergefile,
// cobolParser.RULE_mergekey,
// cobolParser.RULE_inspect_statement,
// cobolParser.RULE_inspect_converting,
// cobolParser.RULE_convert_chars,
// cobolParser.RULE_compare_chars,
// cobolParser.RULE_inspect_replacing,
// cobolParser.RULE_replacing_all,
// cobolParser.RULE_replace_val,
// cobolParser.RULE_replacing_characters,
// cobolParser.RULE_replace_char,
// cobolParser.RULE_inspect_tallying,
// cobolParser.RULE_tallying_for,
// cobolParser.RULE_tallying_for_characters,
// cobolParser.RULE_delim_definition,
// cobolParser.RULE_tallying_for_all,
// cobolParser.RULE_compare_val,
// cobolParser.RULE_delim_val,
// cobolParser.RULE_tally_ctr,
// cobolParser.RULE_src_string,
// cobolParser.RULE_initiate_statement,
// cobolParser.RULE_initialize_statement,
// cobolParser.RULE_replacing,
// cobolParser.RULE_init_value,
// cobolParser.RULE_fld_name,
// cobolParser.RULE_move_statement,
// cobolParser.RULE_if_statement,
// cobolParser.RULE_generate_statement,
// cobolParser.RULE_report_item,
// cobolParser.RULE_exit_statement,
// cobolParser.RULE_exit_program_statement,
// cobolParser.RULE_go_to_statement,
// cobolParser.RULE_proc_name,
// cobolParser.RULE_evaluate_statement,
// cobolParser.RULE_when_condition,
// cobolParser.RULE_subj_item,
// cobolParser.RULE_divide_statement,
// cobolParser.RULE_divide_statement_form1,
// cobolParser.RULE_divide_statement_form2,
// cobolParser.RULE_remaind,
// cobolParser.RULE_divide_num,
// cobolParser.RULE_display_statement,
// cobolParser.RULE_display_statement_form1,
// cobolParser.RULE_display_statement_form2,
// cobolParser.RULE_display_statement_form3,
// cobolParser.RULE_display_statement_form4,
// cobolParser.RULE_src_item,
// cobolParser.RULE_display_upon,
// cobolParser.RULE_disp_f3_line,
// cobolParser.RULE_disp_f3_column,
// cobolParser.RULE_display_form1_clause,
// cobolParser.RULE_display_form2_clause,
// cobolParser.RULE_at_line_number,
// cobolParser.RULE_at_column_number,
// cobolParser.RULE_out_dest,
// cobolParser.RULE_delete_statement,
// cobolParser.RULE_continue_statement,
// cobolParser.RULE_compute_statement,
// cobolParser.RULE_close_statement,
// cobolParser.RULE_close_params,
// cobolParser.RULE_cancel_statement,
// cobolParser.RULE_call_statement,
// cobolParser.RULE_call_giving,
// cobolParser.RULE_call_using,
// cobolParser.RULE_using_arg,
// cobolParser.RULE_using_prefix,
// cobolParser.RULE_argument,
// cobolParser.RULE_prog_name,
// cobolParser.RULE_alter_statement,
// cobolParser.RULE_add_statement,
// cobolParser.RULE_add_grp,
// cobolParser.RULE_add_num,
// cobolParser.RULE_accept_statement,
// cobolParser.RULE_on_exception_variants,
// cobolParser.RULE_at_end_variants,
// cobolParser.RULE_on_size_variants,
// cobolParser.RULE_on_overflow_variants,
// cobolParser.RULE_at_eop_variants,
// cobolParser.RULE_invalid_key_variants,
// cobolParser.RULE_accept_form6,
// cobolParser.RULE_accept6_item,
// cobolParser.RULE_accept_form1,
// cobolParser.RULE_accept_form2,
// cobolParser.RULE_accept_form3,
// cobolParser.RULE_accept_form4,
// cobolParser.RULE_accept_form5,
// cobolParser.RULE_accept_at,
// cobolParser.RULE_accept_at_line,
// cobolParser.RULE_accept_at_column,
// cobolParser.RULE_accept_form4_clause,
// cobolParser.RULE_accept_form3_clause,
// cobolParser.RULE_key_dest_item,
// cobolParser.RULE_def_value,
// cobolParser.RULE_protected_value,
// cobolParser.RULE_prot_fill_lit,
// cobolParser.RULE_prot_size_value,
// cobolParser.RULE_number_value,
// cobolParser.RULE_date_time,
// cobolParser.RULE_dest_item,
// cobolParser.RULE_input_source,
// cobolParser.RULE_at_end,
// cobolParser.RULE_on_exception,
// cobolParser.RULE_on_size,
// cobolParser.RULE_on_overflow,
// cobolParser.RULE_at_eop,
// cobolParser.RULE_invalid_key,
// cobolParser.RULE_file_section,
// cobolParser.RULE_file_description,
// cobolParser.RULE_sort_merge_file_description,
// cobolParser.RULE_working_storage_section,
// cobolParser.RULE_linkage_section,
// cobolParser.RULE_report_section,
// cobolParser.RULE_report_description,
// cobolParser.RULE_screen_section,
// cobolParser.RULE_file_description_entry,
// cobolParser.RULE_sort_merge_file_description_entry,
// cobolParser.RULE_report_description_entry,
// cobolParser.RULE_fd_clause,
// cobolParser.RULE_data_description_entry,
// cobolParser.RULE_level_number,
// cobolParser.RULE_data_description_clause,
// cobolParser.RULE_renames,
// cobolParser.RULE_rename_start,
// cobolParser.RULE_rename_end,
// cobolParser.RULE_value_is,
// cobolParser.RULE_value_is_definition,
// cobolParser.RULE_value_is_definition_part,
// cobolParser.RULE_value_is_definition_thru,
// cobolParser.RULE_external_name,
// cobolParser.RULE_ref_data_name,
// cobolParser.RULE_value_is_literal,
// cobolParser.RULE_occurs,
// cobolParser.RULE_indexed_by,
// cobolParser.RULE_ind_name,
// cobolParser.RULE_key_is,
// cobolParser.RULE_key_name,
// cobolParser.RULE_times_definition,
// cobolParser.RULE_table_size,
// cobolParser.RULE_min_times,
// cobolParser.RULE_max_times,
// cobolParser.RULE_report_group_data_description_entry,
// cobolParser.RULE_report_group_data_description_clause,
// cobolParser.RULE_sign_is,
// cobolParser.RULE_sum,
// cobolParser.RULE_control_foot_name,
// cobolParser.RULE_detail_report_group_name,
// cobolParser.RULE_sum_name,
// cobolParser.RULE_source_name,
// cobolParser.RULE_column_number,
// cobolParser.RULE_type_is_definition,
// cobolParser.RULE_type_control_name,
// cobolParser.RULE_next_group_definition,
// cobolParser.RULE_line_num_definition,
// cobolParser.RULE_line_num,
// cobolParser.RULE_rd_clause,
// cobolParser.RULE_footing_line_rd,
// cobolParser.RULE_last_detail_line,
// cobolParser.RULE_first_detail_line,
// cobolParser.RULE_heading_line,
// cobolParser.RULE_page_size_rd,
// cobolParser.RULE_control_name,
// cobolParser.RULE_report_code,
// cobolParser.RULE_usage,
// cobolParser.RULE_usage_definition,
// cobolParser.RULE_picture,
// cobolParser.RULE_character_string,
// cobolParser.RULE_other_data_item,
// cobolParser.RULE_data_name,
// cobolParser.RULE_sd_clause,
// cobolParser.RULE_report_is,
// cobolParser.RULE_report_name,
// cobolParser.RULE_linage,
// cobolParser.RULE_bottom_lines,
// cobolParser.RULE_top_lines,
// cobolParser.RULE_footing_line,
// cobolParser.RULE_page_size,
// cobolParser.RULE_data_rec,
// cobolParser.RULE_rec_name,
// cobolParser.RULE_value_of_id,
// cobolParser.RULE_value_of_id_definition,
// cobolParser.RULE_label,
// cobolParser.RULE_record,
// cobolParser.RULE_record_definition,
// cobolParser.RULE_depending_item,
// cobolParser.RULE_shortest_rec,
// cobolParser.RULE_longest_rec,
// cobolParser.RULE_screen_description_entry,
// cobolParser.RULE_screen_name,
// cobolParser.RULE_screen_description_clause,
// cobolParser.RULE_scr_pic_using,
// cobolParser.RULE_scr_pic_from,
// cobolParser.RULE_scr_pic_to,
// cobolParser.RULE_nonnumeric_literal,
// cobolParser.RULE_src_number,
// cobolParser.RULE_color_num,
// cobolParser.RULE_program_id,
// cobolParser.RULE_program_name,
// cobolParser.RULE_common_initial,
// cobolParser.RULE_with_ident,
// cobolParser.RULE_ident_string,
// cobolParser.RULE_installation,
// cobolParser.RULE_date_written,
// cobolParser.RULE_date_compiled,
// cobolParser.RULE_security,
// cobolParser.RULE_options_,
// cobolParser.RULE_arithmetic,
// cobolParser.RULE_configuration_section,
// cobolParser.RULE_input_output_section,
// cobolParser.RULE_source_computer,
// cobolParser.RULE_computer_type,
// cobolParser.RULE_with_debugging,
// cobolParser.RULE_object_computer,
// cobolParser.RULE_memory_size,
// cobolParser.RULE_memory_size_amount,
// cobolParser.RULE_memory_size_unit,
// cobolParser.RULE_program_collating,
// cobolParser.RULE_alpha_name,
// cobolParser.RULE_segment_limit,
// cobolParser.RULE_segment_number,
// cobolParser.RULE_special_names,
// cobolParser.RULE_special_names_content,
// cobolParser.RULE_cursor_is,
// cobolParser.RULE_crt_is,
// cobolParser.RULE_predefined_name_relation,
// cobolParser.RULE_predefined_name,
// cobolParser.RULE_switch_definition,
// cobolParser.RULE_switch_clause_on,
// cobolParser.RULE_switch_clause_off,
// cobolParser.RULE_cond_name,
// cobolParser.RULE_switch_name,
// cobolParser.RULE_switch_num,
// cobolParser.RULE_qualified_data_item,
// cobolParser.RULE_currency,
// cobolParser.RULE_currency_definition,
// cobolParser.RULE_currency_string,
// cobolParser.RULE_currency_char,
// cobolParser.RULE_class_,
// cobolParser.RULE_class_name,
// cobolParser.RULE_user_class,
// cobolParser.RULE_symbolic_chars,
// cobolParser.RULE_symb_ch_definition,
// cobolParser.RULE_symb_ch_def_clause,
// cobolParser.RULE_symb_ch_def_in_alphabet,
// cobolParser.RULE_symbol_char,
// cobolParser.RULE_char_val,
// cobolParser.RULE_alphabet,
// cobolParser.RULE_alpha_value,
// cobolParser.RULE_user_alpha,
// cobolParser.RULE_first_literal,
// cobolParser.RULE_last_literal,
// cobolParser.RULE_same_literal,
// cobolParser.RULE_top_of_page_name,
// cobolParser.RULE_user_name,
// cobolParser.RULE_file_control,
// cobolParser.RULE_select,
// cobolParser.RULE_file_status,
// cobolParser.RULE_file_stat,
// cobolParser.RULE_record_key,
// cobolParser.RULE_record_key_definition,
// cobolParser.RULE_seg_key,
// cobolParser.RULE_rec_key,
// cobolParser.RULE_access_mode,
// cobolParser.RULE_reserve,
// cobolParser.RULE_reserve_num,
// cobolParser.RULE_record_delimiter,
// cobolParser.RULE_padding,
// cobolParser.RULE_pad_char,
// cobolParser.RULE_organization,
// cobolParser.RULE_lock_mode,
// cobolParser.RULE_lock_mode_definition,
// cobolParser.RULE_code_set,
// cobolParser.RULE_block_contains,
// cobolParser.RULE_smallest_block,
// cobolParser.RULE_blocksize,
// cobolParser.RULE_assign_to,
// cobolParser.RULE_assign_to_definition,
// cobolParser.RULE_file_spec,
// cobolParser.RULE_file_name,
// cobolParser.RULE_i_o_control,
// cobolParser.RULE_i_o_control_clause,
// cobolParser.RULE_multiple_file,
// cobolParser.RULE_multiple_file_definition,
// cobolParser.RULE_multiple_file_name,
// cobolParser.RULE_pos_integer,
// cobolParser.RULE_rerun,
// cobolParser.RULE_rerun_definition,
// cobolParser.RULE_clock_count,
// cobolParser.RULE_condition_name,
// cobolParser.RULE_rerun_def_file,
// cobolParser.RULE_rec_count,
// cobolParser.RULE_same,
// cobolParser.RULE_same_area_file,
// cobolParser.RULE_apply,
// cobolParser.RULE_apply_definition,
// cobolParser.RULE_window_ptrs,
// cobolParser.RULE_preall_amt,
// cobolParser.RULE_extend_amt,
// cobolParser.RULE_arithmetic_expression,
// cobolParser.RULE_constant,
// cobolParser.RULE_binary_arithmetic_operator,
// cobolParser.RULE_unary_arithmetic_operator,
// cobolParser.RULE_logic_expression,
// cobolParser.RULE_logic_condition,
// cobolParser.RULE_logic_condition_abbrev,
// cobolParser.RULE_logic_operation,
// cobolParser.RULE_bool_condition_name,
// cobolParser.RULE_sign_condition_name,
// cobolParser.RULE_class_condition_name,
// cobolParser.RULE_condition_operator,
// cobolParser.RULE_identifier_result,
// cobolParser.RULE_identifier,
// cobolParser.RULE_arguments,
// cobolParser.RULE_subscripting,
// cobolParser.RULE_reference_modification,
// cobolParser.RULE_leftmost_character_position,
// cobolParser.RULE_length,
// cobolParser.RULE_function_name,
];

export const _RuleTokensMap = new Map<number, (number|string)[]>(_RuleTokens.map(x => [x.ruleId, x.values?x.values:[]]));
